# Generated by Django 3.1.1 on 2020-10-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200929_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'email'), ('github', 'github'), ('kakao', 'kakao')], default='email', max_length=50),
        ),
    ]
