# Generated by Django 3.1.1 on 2020-10-13 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_login_method'),
        ('users', '0005_user_login_method'),
    ]

    operations = [
    ]
