# Generated by Django 3.1.1 on 2020-09-04 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '__first__'),
        ('lists', '0002_auto_20200904_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='lists', to='rooms.Room'),
        ),
    ]
